-- Databricks notebook source
-- MAGIC %python
-- MAGIC dbutils.widgets.text('Partition','')

-- COMMAND ----------

-- MAGIC %python
-- MAGIC spark.conf.set("spark.sql.sources.partitionOverwriteMode", "dynamic")

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS uc_f1_db.l2.CALCULATED_POINTS(
  RACE_ID INT,
  DRIVER_ID INT,
  CONSTRUCTOR_ID INT,
  SPRINT_ID INT,
  POS INT,
  RACE_YEAR INT,
  NAME STRING,
  CONSTRUCTOR STRING,
  POINTS INT,
  SP_POS INT,
  SP_POINTS INT,
  TOTAL_RACE_POINTS INT,
  PARTITION STRING 
)
PARTITIONED BY (PARTITION);

-- COMMAND ----------

INSERT OVERWRITE TABLE uc_f1_db.l2.CALCULATED_POINTS PARTITION (Partition = '${Partition}')

SELECT 
  RESULTS.RACE_ID,
  DRIVERS.DRIVER_ID,
  CONSTRUCTORS.CONSTRUCTOR_ID,
  SP_RESULTS.SPRINT_ID,
  RESULTS.POSITION AS POS,
  RACES.RACE_YEAR,
  CONCAT(DRIVERS.FORENAME,' ',DRIVERS.SURNAME) AS NAME,
  CONSTRUCTORS.NAME AS CONSTRUCTOR,
  CASE 
    WHEN RESULTS.POSITION = 1 THEN 25
    WHEN RESULTS.POSITION = 2 THEN 18
    WHEN RESULTS.POSITION = 3 THEN 15
    WHEN RESULTS.POSITION = 4 THEN 12
    WHEN RESULTS.POSITION = 5 THEN 10
    WHEN RESULTS.POSITION = 6 THEN 8
    WHEN RESULTS.POSITION = 7 THEN 6
    WHEN RESULTS.POSITION = 8 THEN 4
    WHEN RESULTS.POSITION = 9 THEN 2
    WHEN RESULTS.POSITION = 10 THEN 1
    ELSE 0
  END AS POINTS,
  SP_RESULTS.SPRINT_POSITION AS SP_POS,
  CASE
    WHEN SP_RESULTS.SPRINT_POSITION = 1 THEN 8
    WHEN SP_RESULTS.SPRINT_POSITION = 2 THEN 7
    WHEN SP_RESULTS.SPRINT_POSITION = 3 THEN 6
    WHEN SP_RESULTS.SPRINT_POSITION = 4 THEN 5
    WHEN SP_RESULTS.SPRINT_POSITION = 5 THEN 4
    WHEN SP_RESULTS.SPRINT_POSITION = 6 THEN 3
    WHEN SP_RESULTS.SPRINT_POSITION = 7 THEN 2
    WHEN SP_RESULTS.SPRINT_POSITION = 8 THEN 1
    ELSE 0
  END AS SP_POINTS,
  (POINTS + SP_POINTS) AS TOTAL_RACE_POINTS
 FROM uc_f1_db.l1.RESULTS
 LEFT JOIN (SELECT RACE_YEAR,RACE_ID FROM uc_f1_db.l1.RACES WHERE RACES.PARTITION='${Partition}') RACES ON RESULTS.RACE_ID = RACES.RACE_ID
 LEFT JOIN (SELECT DRIVER_ID,FORENAME,SURNAME FROM uc_f1_db.l1.DRIVERS) DRIVERS ON RESULTS.DRIVER_ID = DRIVERS.DRIVER_ID
 LEFT JOIN (SELECT CONSTRUCTOR_ID,NAME FROM uc_f1_db.l1.CONSTRUCTORS) CONSTRUCTORS ON RESULTS.CONSTRUCTOR_ID = CONSTRUCTORS.CONSTRUCTOR_ID
 LEFT JOIN (SELECT SPRINT_ID,RACE_ID,DRIVER_ID,CONSTRUCTOR_ID,SPRINT_POSITION FROM uc_f1_db.l0.SPRINT_RESULTS) SP_RESULTS ON SP_RESULTS.RACE_ID = RESULTS.RACE_ID AND SP_RESULTS.DRIVER_ID = RESULTS.DRIVER_ID AND SP_RESULTS.CONSTRUCTOR_ID = RESULTS.CONSTRUCTOR_ID
 WHERE RESULTS.PARTITION = '${Partition}';


-- COMMAND ----------

select count(*) from uc_f1_db.l2.calculated_points