-- Databricks notebook source
DROP VIEW IF EXISTS uc_f1_db.l2.DOMINANT_DRIVERS;

-- COMMAND ----------

CREATE VIEW IF NOT EXISTS uc_f1_db.l2.DOMINANT_DRIVERS
(
  DRIVER_ID,
  DRIVER ,
  TOTAL_RACES ,
  TOTAL_POINTS ,
  AVG_POINTS 
) AS
(
WITH DRIVERS AS (
    SELECT 
      DRIVER_ID,
      NAME AS DRIVER ,
      COUNT(1) AS TOTAL_RACES,
      SUM(TOTAL_RACE_POINTS) AS TOTAL_POINTS,
      ROUND(AVG(TOTAL_RACE_POINTS),2) AS AVG_POINTS,
      RANK() OVER(ORDER BY AVG(TOTAL_RACE_POINTS) DESC) AS RNK
    FROM uc_f1_db.L2.CALCULATED_POINTS
    GROUP BY DRIVER_ID,NAME
    HAVING COUNT(1) > 25 AND SUM(TOTAL_RACE_POINTS) > 100 
  )
  SELECT 
  DRIVER_ID ,
  DRIVER ,
  TOTAL_RACES ,
  TOTAL_POINTS ,
  AVG_POINTS 
  FROM DRIVERS WHERE RNK <=50
);

-- COMMAND ----------

DROP VIEW IF EXISTS uc_f1_db.l2.DOMINANT_CONSTRUCTORS;

-- COMMAND ----------

CREATE VIEW IF NOT EXISTS uc_f1_db.l2.DOMINANT_CONSTRUCTORS
(
  CONSTRUCTOR_ID ,
  CONSTRUCTOR ,
  TOTAL_RACES ,
  TOTAL_POINTS ,
  AVG_POINTS 
) AS 
(
  WITH CONSTRUCTORS AS (
      SELECT 
      CONSTRUCTOR_ID,
      CONSTRUCTOR,
      COUNT(1) AS TOTAL_RACES,
      SUM(TOTAL_RACE_POINTS) AS TOTAL_POINTS,
      ROUND(AVG(TOTAL_RACE_POINTS),2) AS AVG_POINTS,
      RANK() OVER(ORDER BY AVG(TOTAL_RACE_POINTS) DESC) AS RNK
      FROM uc_f1_db.l2.CALCULATED_POINTS
    GROUP BY CONSTRUCTOR_ID,CONSTRUCTOR
    HAVING COUNT(1) > 50 AND SUM(TOTAL_RACE_POINTS) > 100
  )
  SELECT 
  CONSTRUCTOR_ID ,
  CONSTRUCTOR ,
  TOTAL_RACES ,
  TOTAL_POINTS ,
  AVG_POINTS FROM CONSTRUCTORS WHERE RNK <=20
);