-- Databricks notebook source
WITH CALCULATED_POINTS AS (
  SELECT CONSTRUCTOR
  ,TOTAL_RACE_POINTS AS POINTS
  ,RACE_YEAR
  ,COUNT(*) OVER(PARTITION BY RACE_YEAR,CONSTRUCTOR_ID) AS RACES_PER_YEAR
  FROM uc_f1_db.l2.CALCULATED_POINTS
)
SELECT 
    CONSTRUCTOR ,
    RACE_YEAR,
    COUNT(1) AS TOTAL_RACES,
    SUM(POINTS) AS TOTAL_POINTS,
    ROUND(AVG(POINTS),2) AS AVG_POINTS,
    RANK() OVER(PARTITION BY RACE_YEAR ORDER BY AVG(POINTS) DESC) AS RNK
  FROM CALCULATED_POINTS
  WHERE CONSTRUCTOR IN (SELECT CONSTRUCTOR FROM UC_F1_DB.L2.DOMINANT_CONSTRUCTORS) AND RACES_PER_YEAR >5
  GROUP BY CONSTRUCTOR,RACE_YEAR
  ORDER BY RACE_YEAR,AVG_POINTS